
services:
  app:
    build: .
    container_name: canopy-app-dev
    volumes:
      - .:/app
      - gems:/usr/local/bundle
      - /app/node_modules
      - /app/public/vite-dev
      - /app/tmp/pids  # Важно для server.pid
    ports:
      - "3000:3000"
      - "3035:3035"    # Порт для Vite dev server
    depends_on:
      - pg
      - redis
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      DATABASE_URL: postgres://admin:admin@pg:5432/canopy_company_dev
      REDIS_URL: redis://redis:6379/1
      VITE_RUBY_HOST: localhost  # Для Vite в development
      VITE_RUBY_PORT: 3000
    command: >
      sh -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:prepare &&
        bundle exec rails s -b 0.0.0.0
      "

  pg:
    image: postgres:16.1
    container_name: canopy-pg-dev
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: canopy_company_dev
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: canopy-redis-dev
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

volumes:
  pg_data:
  redis_data:
  gems: