default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  username: admin
  password: admin
  database: canopy_company_dev

test:
  <<: *default
  host: localhost
  username: admin
  password: admin
  database: canopy_company_test

production:
  <<: *default
  host: pg                      # Критически важно для Docker!
  username: admin
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: canopy_company_production