
default: &default
  adapter: postgresql
  encoding: unicode
  #
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: canopy_company_development


production:
  <<: *default
#  database: canopy_company_production
#  username: canopy_company
#  password: <%= ENV["CANOPY_COMPANY_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL']